### ISSUE TITLE
Too less "Turn"

### ISSUE THREAD

**Issue by heroboy** [Bocian-1/10-Books-Full-of-Rails#3]
There is only "U-Turn", and "4 way whirlpool" is too big.
"T Junction" and "4 way intersection" can not turn.

**Comment by Bocian-1** [comment]
Do you mean, that you want a train to be able to turn around in an intersection like this? This is not possible to do in an intersection without losing a lot of throughput and possibly creating deadlock potential. A roundabout could do it, but I chose not to include any as they perform worse in pretty much everything compared to intersections. I mean throughput, deadlock safety, size and even UPS, while the advantage of letting trains do a 180 is rarely useful. If you however still find yourself in 
a need for a train to turn around a U-turn can hold as many as 12 train segments on it's shortest lane so placing it next to a 3-way can serve this exact purpose. I thought of adding a segment for doing this in the middle of a straight rail (like =O=), which would be much more compact and shouldn't cause massive throughput losses, but I worry that people will use it to make roundabouts which as stated above are quite inefficient.
